[[d1_databases]]
binding = "D1"
database_name = "idim"
database_id = "09c09f70-78b7-42b9-934b-8f384f16607e"
migrations_dir = "packages/db/migrations"

[[d1_databases]]
binding = "D1_PROD"
database_name = "idim-prod"
database_id = "f5356adb-0fe4-4e81-a4ea-68844e2847b4"
migrations_dir = "packages/db/migrations"

[[d1_databases]]
binding = "D1_PREV"
database_name = "idim-prev"
database_id = "c84256f2-475e-4942-8443-2e011c957045"
migrations_dir = "packages/db/migrations"

[[kv_namespaces]]
binding = "KV_API_RATE_LIMIT"
id = "a8d149782f724c49a2a9ff689574e4a8"

[[kv_namespaces]]
binding = "KV_CACHE"
id = "a0154b6a-ca3e-4e25-8b1c-fc1dd2f2b7c2"
