version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    healthcheck:
      test: ['CMD', 'pg_isready', '-q', '-d', 'postgres', '-U', 'root']
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: idim
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - 5432:5432
